name: game_flix_flutter
description: A flutter game app consuming Rawg API to display popular video games
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  floor: ^1.4.1
  floor_generator: ^1.3.0
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
