name: game_flix_flutter
description: A flutter game app consuming Rawg API to display popular video games
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  floor: ^1.4.1
  floor_generator: ^1.3.0
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  logger: ^1.1.0
  cached_network_image: ^3.2.3
  fluttericon: ^2.0.0
  carbon_icons: ^0.0.1+2
  carousel_slider: ^4.2.1
  share_plus: ^6.3.1
  fluttertoast: ^8.2.1
  flutter_spinkit: ^5.1.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0
  shared_preferences: ^2.0.20
  mockito: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0

flutter_native_splash:
  image: assets/images/splash.png
  color: "#1A1A1A"
  color_dark: "#1A1A1A"
  image_dark: assets/images/splash.png
  android: true
  ios: true

  android_12:
    image: assets/images/splash.png
    icon_background_color: "#1A1A1A"
    imge_dark: assets/images/splash.png
    icon_background_color_dark: "#1A1A1A"

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  ios: true
  android: true
  image_path: assets/images/splash.png